
export const STUDENT_LIST = [
  "Nguyễn Ngọc Linh An",
  "Trịnh Thị Bình An",
  "Nguyễn Đỗ Hải Anh",
  "Trần Ngọc Quỳnh Anh",
  "Triệu Ngọc Anh",
  "Hoàng Văn Bách",
  "Nguyễn Quang Dũng",
  "Nguyễn Hải Đăng",
  "Lê Hà Gia Hân",
  "Phạm Ngọc Hân",
  "Đặng Gia Huy",
  "Phạm Gia Huy",
  "Ngô Gia Hưng",
  "Nguyễn Tuấn Kiệt",
  "Bùi Hoàng Lâm",
  "Nguyễn Phúc Lâm",
  "Nguyễn Vĩnh Lộc",
  "Nguyễn Trọng Lượng",
  "Dương Khánh Ly",
  "Nguyễn Thanh Mai",
  "Lê Thu Minh",
  "Nguyễn Nhật Minh",
  "Trần Nhật Minh",
  "Lý Hoàng Nam",
  "Trần Khánh Ngân",
  "Cao Khánh Ngọc",
  "Đoàn Bảo Ngọc",
  "Phạm Hồng Ngọc",
  "Nguyễn Phương Nhi",
  "Lê Diệp Mai Phương",
  "Nguyễn Đình Quang",
  "Phạm Anh Thành",
  "Vũ Thanh Thảo",
  "Nguyễn Hoàng Anh Thư",
  "Hoàng Lương Thảo Trân",
  "Nguyễn Minh Tú",
  "Nguyễn Đặng Nhã Uyên",
  "Hà Lương Huy Vũ"
];

export const COLORS = [
  "#FF6B6B", "#4ECDC4", "#45B7D1", "#FFA07A", "#98D8C8", 
  "#F7DC6F", "#BB8FCE", "#82E0AA", "#F1948A", "#85C1E9"
];
